# Generated by Django 3.0.3 on 2021-04-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'position'], 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
