# Generated by Django 3.0.3 on 2021-04-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('blog', '0002_auto_20210405_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='category.Category', verbose_name='دسته بندی'),
        ),
    ]
