# Generated by Django 3.0.3 on 2021-04-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='TextForAuthor',
            field=models.TextField(null=True, verbose_name='دلیل برگشت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('i', 'درحال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
